In [106]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
'''
In this class we create a structure to hold the classification/regression tree.
We need following requirements:
    0- An easy way for user to create the tree
    1- The set of branching nodes
    2- The set of Leaves
    3- For each node we need to get the index of left/right children and the parent

In this class we assume that we have a complete binary tree; we only receive the depth from the user
'''

import numpy as np


class Tree:

    def __init__(self, d):
        self.depth = d
        self.Nodes = [i for i in range(1, np.power(2, d))] #it is all branching nodes
        self.Leaves = [i for i in range(np.power(2, d), np.power(2, d + 1))] # all terminal nodes

    def get_left_children(self, n):
        if n in self.Nodes:
            return 2 * n
        else:
            raise Exception('Node index is not correct')

    def get_right_children(self, n):
        if n in self.Nodes:
            return 2 * n + 1
        else:
            raise Exception('Node index is not correct')

    def get_parent(self, n):
        if (n in self.Nodes) or (n in self.Leaves):
            return np.floor(n/2)
        else:
            raise Exception('Node index is not correct')


    def get_ancestors(self,n):
        ancestors = []
        if (n in self.Nodes) or (n in self.Leaves):
            current = n
            while current != 1:
                current = int(np.floor(current/2))
                ancestors.append(current)
            return ancestors

        else:
            raise Exception('Node index is not correct')

In [ ]:
mytree = Tree(5)

In [15]:
mytree.get_ancestors(6)

[3, 1]

In [16]:
ans = []
current = 6

In [17]:
mytree.get_parent(6)

np.float64(3.0)

In [19]:
import os
data_path = os.getcwd() + '/../../DataSets/'
input_file = 'monk1_enc.csv'
data = pd.read_csv(data_path + input_file)
'''Name of the column in the dataset representing the class label.
In the datasets we have, we assume the label is target. Please change this value at your need'''
label = 'target'

In [53]:
X = data.iloc[:,:-1].to_numpy()

In [49]:
data.iloc[:, -1]

0      1
1      1
2      1
3      1
4      1
      ..
119    1
120    1
121    1
122    1
123    1
Name: target, Length: 124, dtype: int64

In [68]:
data.index

RangeIndex(start=0, stop=124, step=1)

In [26]:
from pathlib import Path

In [45]:
Path.cwd().parent.parent/'DataSets'

PosixPath('/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets')

In [47]:
for i in (Path.cwd().parent.parent/'DataSets').iterdir():
    print(i)

/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/spect_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/tic-tac-toe.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/kr-vs-kp_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/kr-vs-kp.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/balance-scale.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/spect.train
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/house-votes-84.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/house-votes-84.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/hayes-roth.test
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/breast-cancer_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/soybean-small.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/spect.test
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/car_evaluation.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/breast-cancer.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/soybean-small_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/balance-scale.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/kr-vs-kp.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk1.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk3.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk2.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/balance-scale_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/spect.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk1_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/car_evaluation_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/tic-tac-toe.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/soybean-small.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/hayes-roth.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/house-votes-84_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/breast-cancer.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk2_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk3_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/hayes-roth_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/tic-tac-toe_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/hayes-roth.names

In [ ]:
data.iloc[:,-1].unique()

array([1, 0])

In [91]:
np.append(data.iloc[:,-1].unique(), 'bb')

array(['1', '0', 'bb'], dtype='<U21')

In [82]:
data_train.columns[data_train.columns != 'traget']

Index(['Feat_0.1', 'Feat_0.2', 'Feat_0.3', 'Feat_1.1', 'Feat_1.2', 'Feat_1.3',
       'Feat_2.1', 'Feat_3.1', 'Feat_3.2', 'Feat_3.3', 'Feat_4.1', 'Feat_4.2',
       'Feat_4.3', 'Feat_4.4', 'Feat_5.1', 'target'],
      dtype='object')

In [93]:
data.shape[0]

124

In [104]:
data.at[0,'Feat_0.2']

np.int64(0)

In [103]:
data

,Feat_0.1,Feat_0.2,Feat_0.3,Feat_1.1,Feat_1.2,Feat_1.3,Feat_2.1,Feat_3.1,Feat_3.2,Feat_3.3,Feat_4.1,Feat_4.2,Feat_4.3,Feat_4.4,Feat_5.1,target
0,1,0,0,1,0,0,1,1,0,0,0,0,1,0,1,1
1,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0,1
2,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,1
3,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1
4,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,1
120,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0,1
121,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,1
122,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1
123,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,1

In [107]:
X = data.iloc[:, :-1]

In [108]:
X.shape

(124, 15)

In [109]:
y= data.iloc[:,-1]

In [110]:
x_train, x_test, y_train,y_test = train_test_split(X, y, test_size=1.0 - 0.8, shuffle=True,random_state=41)

In [112]:
x_train

,Feat_0.1,Feat_0.2,Feat_0.3,Feat_1.1,Feat_1.2,Feat_1.3,Feat_2.1,Feat_3.1,Feat_3.2,Feat_3.3,Feat_4.1,Feat_4.2,Feat_4.3,Feat_4.4,Feat_5.1
120,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0
62,0,1,0,0,1,0,1,1,0,0,0,1,0,0,0
33,1,0,0,0,0,1,1,0,0,1,0,0,0,1,1
57,0,1,0,1,0,0,0,0,1,0,0,0,1,0,1
66,0,1,0,0,1,0,1,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,0,1,0,0,0,1,1,0,0,1,0,0,1,0,1
98,0,0,1,0,1,0,1,1,0,0,0,0,0,1,0
12,1,0,0,0,1,0,1,1,0,0,0,0,0,1,0
35,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0
64,0,1,0,0,1,0,1,0,1,0,0,0,1,0,0

In [116]:
# Fit a black-box
from sklearn.ensemble import RandomForestClassifier
bbox = RandomForestClassifier(random_state=42, min_samples_leaf=10, max_depth=10)
bbox.fit(x_train, y_train)
# Test performance
print("BB Accuracy : ", np.mean(bbox.predict(x_train) == y_train), "\n")

BB Accuracy :  0.8383838383838383

In [119]:
bbox.predict(x_train)

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0])

In [122]:
labels = np.append(y.unique(), 'bb')

In [123]:
bb_pred = {k:np.zeros(x_train.shape[0]) for k in labels}

In [126]:
bb_pred

{np.str_('1'): array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 np.str_('0'): array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 np.str_('bb'): array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])}

In [127]:
bb_pred['1']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [130]:
bb_pred['1'][np.where(bbox.predict(x_train)==1)]=1

In [131]:
bb_pred['1']

array([1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0.])

In [132]:
bb_pred['0'][np.where(bbox.predict(x_train)==0)]=1

In [135]:
bb_pred['0']+bb_pred['1']

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [137]:
bb_pred['1'][0]

np.float64(1.0)

In [136]:
pd.DataFrame(bb_pred)

      1    0   bb
0   1.0  0.0  0.0
1   1.0  0.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   1.0  0.0  0.0
..  ...  ...  ...
94  0.0  1.0  0.0
95  1.0  0.0  0.0
96  0.0  1.0  0.0
97  0.0  1.0  0.0
98  0.0  1.0  0.0

[99 rows x 3 columns]

In [139]:
str(y[0])

'1'