In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [7]:
'''
In this class we create a structure to hold the classification/regression tree.
We need following requirements:
    0- An easy way for user to create the tree
    1- The set of branching nodes
    2- The set of Leaves
    3- For each node we need to get the index of left/right children and the parent

In this class we assume that we have a complete binary tree; we only receive the depth from the user
'''

import numpy as np


class Tree:

    def __init__(self, d):
        self.depth = d
        self.Nodes = [i for i in range(1, np.power(2, d))] #it is all branching nodes
        self.Leaves = [i for i in range(np.power(2, d), np.power(2, d + 1))] # all terminal nodes

    def get_left_children(self, n):
        if n in self.Nodes:
            return 2 * n
        else:
            raise Exception('Node index is not correct')

    def get_right_children(self, n):
        if n in self.Nodes:
            return 2 * n + 1
        else:
            raise Exception('Node index is not correct')

    def get_parent(self, n):
        if (n in self.Nodes) or (n in self.Leaves):
            return np.floor(n/2)
        else:
            raise Exception('Node index is not correct')


    def get_ancestors(self,n):
        ancestors = []
        if (n in self.Nodes) or (n in self.Leaves):
            current = n
            while current != 1:
                current = int(np.floor(current/2))
                ancestors.append(current)
            return ancestors

        else:
            raise Exception('Node index is not correct')

In [8]:
mytree = Tree(5)

In [9]:
mytree.get_ancestors(6)

[3, 1]

In [10]:
ans = []
current = 6

In [11]:
mytree.get_parent(6)

np.float64(3.0)

In [12]:
import os
data_path = os.getcwd() + '/../../DataSets/'
input_file = 'monk1_enc.csv'
data = pd.read_csv(data_path + input_file)
'''Name of the column in the dataset representing the class label.
In the datasets we have, we assume the label is target. Please change this value at your need'''
label = 'target'

In [13]:
X = data.iloc[:,:-1].to_numpy()

In [14]:
data.iloc[:, -1]

0      1
1      1
2      1
3      1
4      1
      ..
119    1
120    1
121    1
122    1
123    1
Name: target, Length: 124, dtype: int64

In [15]:
data.index

RangeIndex(start=0, stop=124, step=1)

In [16]:
from pathlib import Path

In [17]:
Path.cwd().parent.parent/'DataSets'

PosixPath('/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets')

In [18]:
for i in (Path.cwd().parent.parent/'DataSets').iterdir():
    print(i)

/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/spect_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/tic-tac-toe.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/kr-vs-kp_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/kr-vs-kp.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/balance-scale.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/spect.train
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/house-votes-84.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/house-votes-84.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/hayes-roth.test
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/breast-cancer_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/soybean-small.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/spect.test
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/car_evaluation.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/breast-cancer.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/soybean-small_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/balance-scale.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/kr-vs-kp.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk1.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk3.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk2.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/balance-scale_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/spect.names
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk1_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/car_evaluation_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/tic-tac-toe.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/soybean-small.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/hayes-roth.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/house-votes-84_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/breast-cancer.data
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk2_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/monk3_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/hayes-roth_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/tic-tac-toe_enc.csv
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets/hayes-roth.names

In [19]:
data.iloc[:,-1].unique()

array([1, 0])

In [20]:
np.append(data.iloc[:,-1].unique(), 'bb')

array(['1', '0', 'bb'], dtype='<U21')

In [21]:
data_train.columns[data_train.columns != 'traget']

NameError: name 'data_train' is not defined

In [ ]:
data.shape[0]

124

In [ ]:
data.at[0,'Feat_0.2']

np.int64(0)

In [ ]:
data

,Feat_0.1,Feat_0.2,Feat_0.3,Feat_1.1,Feat_1.2,Feat_1.3,Feat_2.1,Feat_3.1,Feat_3.2,Feat_3.3,Feat_4.1,Feat_4.2,Feat_4.3,Feat_4.4,Feat_5.1,target
0,1,0,0,1,0,0,1,1,0,0,0,0,1,0,1,1
1,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0,1
2,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,1
3,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1
4,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,1
120,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0,1
121,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,1
122,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1
123,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,1

In [52]:
X = data.iloc[:, :-1]

In [53]:
X.shape

(124, 15)

In [54]:
X

,Feat_0.1,Feat_0.2,Feat_0.3,Feat_1.1,Feat_1.2,Feat_1.3,Feat_2.1,Feat_3.1,Feat_3.2,Feat_3.3,Feat_4.1,Feat_4.2,Feat_4.3,Feat_4.4,Feat_5.1
0,1,0,0,1,0,0,1,1,0,0,0,0,1,0,1
1,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0
2,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1
3,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0
4,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0
120,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0
121,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0
122,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0
123,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0

In [29]:
y= data.iloc[:,-1]

In [41]:
np.unique(y.to_numpy())

array([0, 1])

In [ ]:
np.append(y.unique(), 'bb')[:-1]

array(['1', '0', 'bb'], dtype='<U21')

In [ ]:
labels = np.append(self.y.unique(), 'bb') # all classed k in K and bb

In [55]:
x_train, x_test, y_train,y_test = train_test_split(X, y, test_size=1.0 - 0.8, shuffle=True,random_state=41)

In [59]:
x_train.index

Index([120,  62,  33,  57,  66,  71,   0,  43,  39,  24,  38, 118,  79,  74,
        95,  63,  18,  42, 123,  10,  40,  77,  30,  73,  47, 114, 113,   7,
        45,  11,  48,  91,  60,  72,  29,  36, 119, 107,  15,  90, 106, 105,
        87,  97,   8,  21, 116,  31,  46, 100,  22,  44,   5,  20,  69, 104,
       111, 121,  76,   1,  59,   4,  58,  34, 103,  13,  19,  53,  28,  81,
        17,  55,  52, 101,  75,  88,  92,  51,  61,  86,  84,  70,  50, 122,
         3,  56, 108, 109,  26,  85,  23,  89, 115,  65,  80,  98,  12,  35,
        64],
      dtype='int64')

In [61]:
x_train.apply(lambda x: x.index)

,Feat_0.1,Feat_0.2,Feat_0.3,Feat_1.1,Feat_1.2,Feat_1.3,Feat_2.1,Feat_3.1,Feat_3.2,Feat_3.3,Feat_4.1,Feat_4.2,Feat_4.3,Feat_4.4,Feat_5.1
120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120
62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62
33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33
57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57
66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80
98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98
12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35
64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64

In [62]:
x_train.index

Index([120,  62,  33,  57,  66,  71,   0,  43,  39,  24,  38, 118,  79,  74,
        95,  63,  18,  42, 123,  10,  40,  77,  30,  73,  47, 114, 113,   7,
        45,  11,  48,  91,  60,  72,  29,  36, 119, 107,  15,  90, 106, 105,
        87,  97,   8,  21, 116,  31,  46, 100,  22,  44,   5,  20,  69, 104,
       111, 121,  76,   1,  59,   4,  58,  34, 103,  13,  19,  53,  28,  81,
        17,  55,  52, 101,  75,  88,  92,  51,  61,  86,  84,  70,  50, 122,
         3,  56, 108, 109,  26,  85,  23,  89, 115,  65,  80,  98,  12,  35,
        64],
      dtype='int64')

In [45]:
# Fit a black-box
from sklearn.ensemble import RandomForestClassifier
bbox = RandomForestClassifier(random_state=42, min_samples_leaf=10, max_depth=10)
bbox.fit(x_train, y_train)
# Test performance
print("BB Accuracy : ", np.mean(bbox.predict(x_train) == y_train), "\n")

BB Accuracy :  0.8383838383838383

In [46]:
bbox.predict(x_train)

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0])

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
bbox.predict(x_train)

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0])

In [ ]:
y_train

NameError: name 'y_train' is not defined

In [ ]:
labels = np.append(y.unique(), 'bb')

In [ ]:
bb_pred = {k:np.zeros(x_train.shape[0]) for k in labels}

In [ ]:
bb_pred

{np.str_('1'): array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 np.str_('0'): array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 np.str_('bb'): array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])}

In [ ]:
bb_pred['1']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
bb_pred['1'][np.where(bbox.predict(x_train)==1)]=1

In [ ]:
bb_pred['1']

array([1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0.])

In [ ]:
bb_pred['0'][np.where(bbox.predict(x_train)==0)]=1

In [ ]:
bb_pred['0']+bb_pred['1']

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
bb_pred['1'][0]

np.float64(1.0)

In [ ]:
pd.DataFrame(bb_pred)

      1    0   bb
0   1.0  0.0  0.0
1   1.0  0.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   1.0  0.0  0.0
..  ...  ...  ...
94  0.0  1.0  0.0
95  1.0  0.0  0.0
96  0.0  1.0  0.0
97  0.0  1.0  0.0
98  0.0  1.0  0.0

[99 rows x 3 columns]

In [ ]:
str(y[0])

'1'

In [ ]:
import numpy as np

In [ ]:
np.array([1,2])

array([1, 2])

In [ ]:
y

NameError: name 'y' is not defined

In [63]:
import shutil
print(shutil.which("dot"))

None

In [64]:
[10**-2, 10**-3, 10**-4]

[0.01, 0.001, 0.0001]

In [66]:
len([0.1,0.2,0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,0.95])

10

In [67]:
eta = lambda X,lambdaValue : min([ (1 / X.shape[0]) / 2, lambdaValue / 2])

In [68]:
eta(x_train, 10**-2)

0.005

In [72]:
def show(x,y):
    print(x, y)

In [74]:
show(**{"x":154, "y":26})

154 26

In [79]:
list({"x":154, "y":26}.values())

[154, 26]

In [98]:
class Dataset():
    """Class representing a dataset loaded from a csv file.
    csv file is after rule mining"""
    def __init__(self, dataset_name, X, y, features, prediction):
        self.name = dataset_name
        self.X = X
        self.features = features
        self.y = y
        self.prediction = prediction
        self.preprocessed = False
    

    @classmethod
    def from_csv(cls, fname, dataset_name ):
        """
        Load a dataset from a csv file. The csv file must contain n_samples+1 rows, each with n_features+1
        columns. The last column of each sample is its prediction class, and the first row of the file
        contains the feature names and prediction class name.
        
        Parameters
        ----------
        fname : str
            File name of the csv data file
        
        Returns
        -------
        X : array-like, shape = [n_samples, n_features]
            The sample data

        y : array-line, shape = [n_samples]
            The target values for the sample data
        
        features : list
            A list of strings of length n_features. Specifies the names of each of the features.

        prediction_name : str
            The name of the prediction class
        """
        df = pd.read_csv(fname)
        X = df.iloc[:, :-1].to_numpy()
        y = df.iloc[:, -1].to_numpy()
        features = df.columns[:-1].tolist()
        prediction = df.columns[-1]
        return cls(dataset_name, X, y, features, prediction)


    def train_test_split(self, train_proportion, random_state):
        X_train, X_test, y_train, y_test = train_test_split(self.X, self.y, test_size=1.0 - train_proportion, shuffle=True,random_state=random_state)
        X_dict = {'train': X_train, 'test':X_test }
        y_dict = {'train': y_train, 'test':y_test }
        return X_dict, y_dict
    

    def pre_process (self):
        """This method apply all modifications regarding demographic subgroups
        """
        raise NotImplementedError("This method is not implemented yet")
        


    def split_data_as_dict(self, splits, random_state_param=42):
        """This method split data to train and test set after preprocessing
        # it was called get_data_norulemining in hybridCORELS
        Args:
            splits (dict): example {"train" : 0.8, "test" : 0.2}
            random_state_param (int, optional):  Defaults to 42.

        Returns:
            dict: the output is X={'train':X_train,'test': X_test}
        and y={'train':y_train,'test': y_test}
        """

        # Generate splits
        assert len(splits) <= 3, "We only support splitting the data to up to 3 folds"
        split_names = list(splits.keys())
        split_ratios = list(splits.values())
        assert np.sum(split_ratios) == 1, "The split ratios must sum up to one"
        X_dict = {}
        y_dict = {}
        X_1, X_2, y_1, y_2 = train_test_split(self.X, self.y, train_size=split_ratios[0],
                                            shuffle=True, random_state=random_state_param)
        X_dict[split_names[0]] = X_1
        y_dict[split_names[0]] = y_1
        if len(splits) == 2:
            X_dict[split_names[1]] = X_2
            y_dict[split_names[1]] = y_2
        else:
            sub_ratio = split_ratios[1] / (split_ratios[1] + split_ratios[2])
            X_2, X_3, y_2, y_3 = train_test_split(X_2, y_2, train_size=sub_ratio,
                                            shuffle=True, random_state=random_state_param)
            X_dict[split_names[1]] = X_2
            y_dict[split_names[1]] = y_2
            X_dict[split_names[2]] = X_3
            y_dict[split_names[2]] = y_3
        return X_dict, y_dict, self.features, self.prediction
    
    def split_data_as_dict_withsize(self, splits, random_state_param=42):
        """This method split data to train and test set after preprocessing
        # it was called get_data_norulemining in hybridCORELS
        Args:
            splits (dict): example {"train" : 0.8, "test" : 0.2}
            random_state_param (int, optional):  Defaults to 42.

        Returns:
            dict: the output is X={'train':X_train,'test': X_test}
        and y={'train':y_train,'test': y_test}
        """

        # Generate splits
        assert len(splits) <= 3, "We only support splitting the data to up to 3 folds"
        split_names = list(splits.keys())
        split_ratios = list(splits.values())
        assert np.sum(split_ratios) <= self.X.shape[0]
        X_dict = {}
        y_dict = {}
        X_1, X_2, y_1, y_2 = train_test_split(self.X, self.y, train_size=split_ratios[0],
                                            shuffle=True, random_state=random_state_param)
        X_dict[split_names[0]] = X_1
        y_dict[split_names[0]] = y_1
        if len(splits) == 2:
            X_dict[split_names[1]] = X_2
            y_dict[split_names[1]] = y_2
        else:
            # sub_ratio = split_ratios[1] / (split_ratios[1] + split_ratios[2])
            X_2, X_3, y_2, y_3 = train_test_split(X_2, y_2, train_size=split_ratios[1], test_size= split_ratios[2],
                                            shuffle=True, random_state=random_state_param)
            X_dict[split_names[1]] = X_2
            y_dict[split_names[1]] = y_2
            X_dict[split_names[2]] = X_3
            y_dict[split_names[2]] = y_3
        return X_dict, y_dict, self.features, self.prediction

    def to_df(self):
        return pd.DataFrame(self.X, columns=self.features)
    
    
    def to_df_from_dict(self, X_dict):
        df_X = {}
        for key, val in X_dict.items():
            df_X[key] = pd.DataFrame(val, columns=self.features)
        return df_X

In [81]:
data_path

'/Users/ziba/programming/optimization/Strong_Tree/StrongTree/Code/StrongTree/../../DataSets/'

In [99]:
DataDIR = Path.cwd().parent.parent/'DataSets'

random_state = 42
time_limit=100
#split information
train_proportion=0.8
# Load data
dataset_name = 'compas.csv'
Datapath = DataDIR/dataset_name
my_data = Dataset.from_csv(Datapath, dataset_name)

In [102]:
my_data.X.shape[0]

7214

In [105]:
X,y ,_,_=my_data.split_data_as_dict_withsize({"train" : 1000,"validation": 1000, "test" : 1000},42)

In [106]:
X['validation'].shape

(1000, 27)

In [107]:
5*5*3*10

750

In [112]:
for i in (Path.cwd().parent.parent).iterdir():
    print(i)

/Users/ziba/programming/optimization/Strong_Tree/StrongTree/requirements.txt
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/DataSets
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/Code
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/README.md
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/Results
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/.gitignore
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/logo.png
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/.git
/Users/ziba/programming/optimization/Strong_Tree/StrongTree/Plots

In [117]:
Path.cwd().parent.parent/'Results'/'HybridDT'

PosixPath('/Users/ziba/programming/optimization/Strong_Tree/StrongTree/Results/HybridDT')

In [118]:
{'dataset_name': 'compas', 'model': 'HybridDTClassifier_post', 'depth': 1, 'lambdaa': 0.01, 'min_transp': 0.8, 'seed': 1}

{'dataset_name': 'compas',
 'model': 'HybridDTClassifier_post',
 'depth': 1,
 'lambdaa': 0.01,
 'min_transp': 0.8,
 'seed': 1}

In [119]:
ESTIMATORS = {

    "HybridDTClassifier_post": {
        "build": lambda bbox, h: HybridDT(
            black_box_classifier=bbox,
            depth = h["depth"],
            lambdaa=h["lambdaa"],
            eta = h["eta"],
            min_transp=h["min_transp"],
            estimator=h["estimator"],
           
        ),
        "fit": lambda model, X, y, h: model.fit(X, y, features=h["features"],time_limit=h["time_limit"]),
        "hparams": {
            "depth":[1,2,3,4,5],
            "lambdaa": [10**-2, 10**-3, 10**-4],
            "eta" : lambda X,lambdaValue : min([ (1 / X.shape[0]) / 2, lambdaValue / 2]),
            "min_transp": [0.1,0.2,0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,0.95]
        }
    } }

eta = lambda X,lambdaValue : min([ (1 / X.shape[0]) / 2, lambdaValue / 2])
    # HybridDT_classifier = HybridDT(black_box_classifier=bbox,depth = 3, lambdaa = 0.001, eta = 0.1,min_transp = 0.7,
    #                                 estimator = 'FlowOCT', verbosity = ['hybrid'], random_state=42, bb_pretrained=False )
    
    # HybridDT_classifier.fit(df_X['train'], y['train'], features, time_limit=time_limit)

n_seeds = 5
DATASETS = ["compas", "adult", "acs_employ"]
SEEDS = [1,2,3,4,5]


EXPERIMENTS = []

for dataset in DATASETS:
    for seed in SEEDS:
        for model in ESTIMATORS:
            for d in ESTIMATORS[model]['hparams']['depth']:
                for lambdaa_val in ESTIMATORS[model]['hparams']['lambdaa']:
                        for alpha_val in ESTIMATORS[model]['hparams']['min_transp']:
                            EXPERIMENTS.append({
                                "dataset_name": dataset,
                                "model": model,
                                "depth":d ,
                                "lambdaa": lambdaa_val,
                                "min_transp": alpha_val,
                                "seed": seed
                            })

In [142]:
EXPERIMENTS[42]

{'dataset_name': 'compas',
 'model': 'HybridDTClassifier_post',
 'depth': 2,
 'lambdaa': 0.001,
 'min_transp': 0.3,
 'seed': 1}

In [210]:
result_path = Path(Path("/Users/ziba/programming/optimization/Strong_Tree"), "StrongTree", "Results", "HybridDT", "HybridDTClassifier_post")

In [211]:
for i in result_path.iterdir():
    print(i.stem)

compas_seed1_depth1_lambdaa0.01_min_transp0.1
compas_seed1_depth1_lambdaa0.01_min_transp0.2
compas_seed1_depth1_lambdaa0.01_min_transp0.3
compas_seed1_depth1_lambdaa0.01_min_transp0.95
compas_seed1_depth1_lambdaa0.01_min_transp0.7
compas_seed1_depth1_lambdaa0.01_min_transp0.6
compas_seed1_depth1_lambdaa0.001_min_transp0.8
compas_seed1_depth1_lambdaa0.01_min_transp0.4
compas_seed1_depth1_lambdaa0.01_min_transp0.5
compas_seed1_depth1_lambdaa0.001_min_transp0.9
compas_seed1_depth1_lambdaa0.0001_min_transp0.95
compas_seed1_depth1_lambdaa0.0001_min_transp0.1
compas_seed1_depth1_lambdaa0.0001_min_transp0.2
compas_seed1_depth1_lambdaa0.0001_min_transp0.3
compas_seed1_depth1_lambdaa0.0001_min_transp0.7
compas_seed1_depth1_lambdaa0.0001_min_transp0.6
compas_seed1_depth1_lambdaa0.0001_min_transp0.4
compas_seed1_depth1_lambdaa0.0001_min_transp0.5
compas_seed1_depth1_lambdaa0.0001_min_transp0.8
compas_seed1_depth1_lambdaa0.0001_min_transp0.9
compas_seed1_depth1_lambdaa0.001_min_transp0.95
compas_seed1_depth1_lambdaa0.001_min_transp0.4
compas_seed1_depth1_lambdaa0.01_min_transp0.8
compas_seed1_depth1_lambdaa0.01_min_transp0.9
compas_seed1_depth1_lambdaa0.001_min_transp0.5
compas_seed1_depth1_lambdaa0.001_min_transp0.7
compas_seed1_depth1_lambdaa0.001_min_transp0.6
compas_seed1_depth1_lambdaa0.001_min_transp0.2
compas_seed1_depth1_lambdaa0.001_min_transp0.3
compas_seed1_depth1_lambdaa0.001_min_transp0.1

In [212]:
import pickle
all_models = {}
for f in result_path.iterdir():
    key = f.stem
    if True: #f"min_transp{0.9}" in f.name 
        with open(f, "rb") as f:
            
            one_round = pickle.load(f)
            all_models[key]=one_round

In [213]:
len(all_models)

30

In [215]:
all_models

{'compas_seed1_depth1_lambdaa0.01_min_transp0.1': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.1,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'acc': np.float64(0.7235),
   'transparency': np.float64(0.2165)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'acc': np.float64(0.6455),
   'transparency': np.float64(0.205)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 1], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'acc': np.float64(0.6645),
   'transparency': np.float64(0.218)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.01_min_transp0.2': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.2,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'acc': np.float64(0.7235),
   'transparency': np.float64(0.2165)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'acc': np.float64(0.6455),
   'transparency': np.float64(0.205)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 1], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'acc': np.float64(0.6645),
   'transparency': np.float64(0.218)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.01_min_transp0.3': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.3,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'acc': np.float64(0.707),
   'transparency': np.float64(0.3215)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'acc': np.float64(0.651),
   'transparency': np.float64(0.296)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 1], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'acc': np.float64(0.6625),
   'transparency': np.float64(0.3235)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.01_min_transp0.95': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.95,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6295),
   'transparency': np.float64(1.0)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.624),
   'transparency': np.float64(1.0)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(1.0)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.01_min_transp0.7': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.7,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6295),
   'transparency': np.float64(1.0)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.624),
   'transparency': np.float64(1.0)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(1.0)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.01_min_transp0.6': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.6,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 0, 1, 1], shape=(2000,)),
   'acc': np.float64(0.65),
   'transparency': np.float64(0.6785)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.62),
   'transparency': np.float64(0.704)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 0, 1], shape=(2000,)),
   'acc': np.float64(0.6275),
   'transparency': np.float64(0.6765)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.001_min_transp0.8': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.8,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6295),
   'transparency': np.float64(1.0)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.624),
   'transparency': np.float64(1.0)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(1.0)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.01_min_transp0.4': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.4,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 1, 0, 1], shape=(2000,)),
   'pred_type': array([1, 0, 0, ..., 0, 0, 1], shape=(2000,)),
   'acc': np.float64(0.6555),
   'transparency': np.float64(0.443)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'acc': np.float64(0.626),
   'transparency': np.float64(0.4235)},
  'validation': {'predictions': array([0, 1, 0, ..., 0, 1, 1], shape=(2000,)),
   'pred_type': array([0, 1, 0, ..., 0, 0, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(0.3885)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.01_min_transp0.5': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.5,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 1, 1, ..., 1, 1, 0], shape=(2000,)),
   'acc': np.float64(0.654),
   'transparency': np.float64(0.557)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 0, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6005),
   'transparency': np.float64(0.5765)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 0, 1], shape=(2000,)),
   'pred_type': array([1, 0, 1, ..., 1, 1, 0], shape=(2000,)),
   'acc': np.float64(0.609),
   'transparency': np.float64(0.6115)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.001_min_transp0.9': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.9,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6295),
   'transparency': np.float64(1.0)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.624),
   'transparency': np.float64(1.0)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(1.0)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.95': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.95,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6295),
   'transparency': np.float64(1.0)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.624),
   'transparency': np.float64(1.0)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(1.0)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.1': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.1,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'acc': np.float64(0.7235),
   'transparency': np.float64(0.2165)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'acc': np.float64(0.6455),
   'transparency': np.float64(0.205)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 1], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'acc': np.float64(0.6645),
   'transparency': np.float64(0.218)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.2': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.2,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'acc': np.float64(0.7235),
   'transparency': np.float64(0.2165)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'acc': np.float64(0.6455),
   'transparency': np.float64(0.205)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 1], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'acc': np.float64(0.6645),
   'transparency': np.float64(0.218)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.3': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.3,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'acc': np.float64(0.707),
   'transparency': np.float64(0.3215)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'acc': np.float64(0.651),
   'transparency': np.float64(0.296)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 1], shape=(2000,)),
   'pred_type': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'acc': np.float64(0.6625),
   'transparency': np.float64(0.3235)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.7': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.7,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6295),
   'transparency': np.float64(1.0)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.624),
   'transparency': np.float64(1.0)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(1.0)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.6': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.6,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 0, 1, 1], shape=(2000,)),
   'acc': np.float64(0.65),
   'transparency': np.float64(0.6785)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.62),
   'transparency': np.float64(0.704)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 0, 1], shape=(2000,)),
   'acc': np.float64(0.6275),
   'transparency': np.float64(0.6765)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.4': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.4,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 1, 0, 1], shape=(2000,)),
   'pred_type': array([1, 0, 0, ..., 0, 0, 1], shape=(2000,)),
   'acc': np.float64(0.6555),
   'transparency': np.float64(0.443)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'acc': np.float64(0.626),
   'transparency': np.float64(0.4235)},
  'validation': {'predictions': array([0, 1, 0, ..., 0, 1, 1], shape=(2000,)),
   'pred_type': array([0, 1, 0, ..., 0, 0, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(0.3885)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.5': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.5,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 1, 1, ..., 1, 1, 0], shape=(2000,)),
   'acc': np.float64(0.654),
   'transparency': np.float64(0.557)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 0, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6005),
   'transparency': np.float64(0.5765)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 0, 1], shape=(2000,)),
   'pred_type': array([1, 0, 1, ..., 1, 1, 0], shape=(2000,)),
   'acc': np.float64(0.609),
   'transparency': np.float64(0.6115)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.8': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.8,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6295),
   'transparency': np.float64(1.0)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.624),
   'transparency': np.float64(1.0)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(1.0)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.0001_min_transp0.9': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.9,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6295),
   'transparency': np.float64(1.0)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.624),
   'transparency': np.float64(1.0)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(1.0)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.001_min_transp0.95': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.95,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([0, 0, 0, ..., 1, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.6295),
   'transparency': np.float64(1.0)},
  'test': {'predictions': array([0, 0, 0, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.624),
   'transparency': np.float64(1.0)},
  'validation': {'predictions': array([0, 0, 0, ..., 0, 1, 0], shape=(2000,)),
   'pred_type': array([1, 1, 1, ..., 1, 1, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(1.0)},
  'only_bb_acc': np.float64(0.7275),
  'status': 2,
  'optgap': 0.0},
 'compas_seed1_depth1_lambdaa0.001_min_transp0.4': {'model': 'HybridDTClassifier_post',
  'dataset': 'compas',
  'seed': 1,
  'depth': 1,
  'min_transp': 0.4,
  'n_branches': np.float64(1.0),
  'n_leaves': np.float64(2.0),
  'train': {'predictions': array([1, 0, 0, ..., 1, 0, 1], shape=(2000,)),
   'pred_type': array([1, 0, 0, ..., 0, 0, 1], shape=(2000,)),
   'acc': np.float64(0.6555),
   'transparency': np.float64(0.443)},
  'test': {'predictions': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'pred_type': array([0, 0, 1, ..., 0, 0, 0], shape=(2000,)),
   'acc': np.float64(0.626),
   'transparency': np.float64(0.4235)},
  'validation': {'predictions': array([0, 1, 0, ..., 0, 1, 1], shape=(2000,)),
   'pred_type': array([0, 1, 0, ..., 0, 0, 1], shape=(2000,)),
   'acc': np.float64(0.631),
   'transparency': np.float64(0.3885)},

In [216]:
np.unique_counts([all_models[i]['status'] for i in all_models])

UniqueCountsResult(values=array([2]), counts=array([30]))

In [217]:

[int(i.split("depth")[1].split("_")[0]) for i in all_models]

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [218]:
for i,j,k in zip([int(i.split("depth")[1].split("_")[0]) for i in all_models],[float(i.split("min_transp")[-1]) for i in all_models], [all_models[i]['train']['transparency']  for i in all_models]):
    print(i,j,k)

1 0.1 0.2165
1 0.2 0.2165
1 0.3 0.3215
1 0.95 1.0
1 0.7 1.0
1 0.6 0.6785
1 0.8 1.0
1 0.4 0.443
1 0.5 0.557
1 0.9 1.0
1 0.95 1.0
1 0.1 0.2165
1 0.2 0.2165
1 0.3 0.3215
1 0.7 1.0
1 0.6 0.6785
1 0.4 0.443
1 0.5 0.557
1 0.8 1.0
1 0.9 1.0
1 0.95 1.0
1 0.4 0.443
1 0.8 1.0
1 0.9 1.0
1 0.5 0.557
1 0.7 1.0
1 0.6 0.6785
1 0.2 0.2165
1 0.3 0.3215
1 0.1 0.2165

In [219]:
list(all_models.keys())[3] #2 0.5 0.323

'compas_seed1_depth1_lambdaa0.01_min_transp0.95'

In [207]:

ESTIMATORS = {

    "HybridDTClassifier_post": {
        "build": lambda bbox, h: HybridDT(
            black_box_classifier=bbox,
            depth = h["depth"],
            lambdaa=h["lambdaa"],
            eta = h["eta"],
            min_transp=h["min_transp"],
            estimator=h["estimator"],
           
        ),
        "fit": lambda model, X, y, h: model.fit(X, y, features=h["features"],time_limit=h["time_limit"]),
        "hparams": {
            "depth":[1,2,3,4,5],
            "lambdaa": [10**-2, 10**-3, 10**-4],
            "eta" : lambda X,lambdaValue : min([ (1 / X.shape[0]) / 2, lambdaValue / 2]),
            "min_transp": [0.1,0.2,0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,0.95]
        }
    } }

eta = lambda X,lambdaValue : min([ (1 / X.shape[0]) / 2, lambdaValue / 2])
    # HybridDT_classifier = HybridDT(black_box_classifier=bbox,depth = 3, lambdaa = 0.001, eta = 0.1,min_transp = 0.7,
    #                                 estimator = 'FlowOCT', verbosity = ['hybrid'], random_state=42, bb_pretrained=False )
    
    # HybridDT_classifier.fit(df_X['train'], y['train'], features, time_limit=time_limit)

n_seeds = 5
DATASETS = ["compas", "adult", "acs_employ"]
SEEDS = [1,2,3,4,5]


EXPERIMENTS = []

for dataset in DATASETS:
    for seed in SEEDS:
        for model in ESTIMATORS:
            for d in ESTIMATORS[model]['hparams']['depth']:
                for lambdaa_val in ESTIMATORS[model]['hparams']['lambdaa']:
                        for alpha_val in ESTIMATORS[model]['hparams']['min_transp']:
                            EXPERIMENTS.append({
                                "dataset_name": dataset,
                                "model": model,
                                "depth":d ,
                                "lambdaa": lambdaa_val,
                                "min_transp": alpha_val,
                                "seed": seed
                            })

In [208]:
len(EXPERIMENTS)

2250

In [209]:
filtered_experiments = []

for cfg in EXPERIMENTS:
    if cfg["dataset_name"] != 'compas':
        continue

    filtered_experiments.append(cfg)
    # print(cfg, filtered_experiments.index(cfg))

#print(f"Total filtered jobs: {len(filtered_experiments)}")
print("number of experimnets ",len(filtered_experiments))

number of experimnets  750

In [221]:
callback_history =[{'time': 0.05834078788757324, 'obj': 0.48813030670592655, 'best_bound': 1e+100, 'gap': 2.048633297834647e+100, 'train_acc': 0.4881303067059435, 'train_transparency': 1.0}, {'time': 4.1701109409332275, 'obj': 0.511869693294053, 'best_bound': 15.000000000000897, 'gap': 28.3043331076526, 'train_acc': 0.5118696932940565, 'train_transparency': 1.0}, {'time': 69.53902077674866, 'obj': 0.5355823600762393, 'best_bound': 0.999850000000013, 'gap': 0.8668463984842332, 'train_acc': 0.5357823600762432, 'train_transparency': 1.0}, {'time': 69.7161808013916, 'obj': 0.5366200311904298, 'best_bound': 0.999850000000013, 'gap': 0.8632364464329833, 'train_acc': 0.5368220412406862, 'train_transparency': 0.9597989949748744}, {'time': 69.82375693321228, 'obj': 0.5366211575116921, 'best_bound': 0.999850000000013, 'gap': 0.8632325356613019, 'train_acc': 0.5368220412406862, 'train_transparency': 0.9823254202044707}, {'time': 69.88840889930725, 'obj': 0.5367933373765328, 'best_bound': 0.999850000000013, 'gap': 0.8626348920174282, 'train_acc': 0.53699532143476, 'train_transparency': 0.9603188355570959}, {'time': 86.20882201194763, 'obj': 0.5859735054583198, 'best_bound': 0.9998499999999936, 'gap': 0.7063058153422138, 'train_acc': 0.586380176745798, 'train_transparency': 0.8665742505631606}, {'time': 86.27461099624634, 'obj': 0.5937711141916413, 'best_bound': 0.9998499999999936, 'gap': 0.6838980140709391, 'train_acc': 0.5941777854791197, 'train_transparency': 0.8665742505631606}, {'time': 86.3926899433136, 'obj': 0.6329266504938413, 'best_bound': 0.9998499999999936, 'gap': 0.5797249163388208, 'train_acc': 0.6333391093398024, 'train_transparency': 0.7508230809218506}, {'time': 86.61863684654236, 'obj': 0.6452295442730821, 'best_bound': 0.9998499999999936, 'gap': 0.5496035618245413, 'train_acc': 0.6456420031190435, 'train_transparency': 0.7508230809218506}, {'time': 87.00734496116638, 'obj': 0.6455744151793374, 'best_bound': 0.9998499999999936, 'gap': 0.5487757514712538, 'train_acc': 0.6459885635071911, 'train_transparency': 0.7170334430774563}, {'time': 150.02755188941956, 'obj': 0.6554510136891317, 'best_bound': 0.9998458448405759, 'gap': 0.5254318384726525, 'train_acc': 0.6558655345693987, 'train_transparency': 0.7095823947322821}, {'time': 150.31259083747864, 'obj': 0.6752061774389126, 'best_bound': 0.9998458448405759, 'gap': 0.48080079574069673, 'train_acc': 0.675619476693814, 'train_transparency': 0.7340149020966904}, {'time': 158.06805086135864, 'obj': 0.6819644169121435, 'best_bound': 0.9998458448405759, 'gap': 0.466126120432739, 'train_acc': 0.6823774042626928, 'train_transparency': 0.7402529890833478}]

In [227]:
[i['train_acc'] for i in callback_history]

[0.4881303067059435,
 0.5118696932940565,
 0.5357823600762432,
 0.5368220412406862,
 0.5368220412406862,
 0.53699532143476,
 0.586380176745798,
 0.5941777854791197,
 0.6333391093398024,
 0.6456420031190435,
 0.6459885635071911,
 0.6558655345693987,
 0.675619476693814,
 0.6823774042626928]

In [226]:
callback_history

[{'time': 0.05834078788757324,
  'obj': 0.48813030670592655,
  'best_bound': 1e+100,
  'gap': 2.048633297834647e+100,
  'train_acc': 0.4881303067059435,
  'train_transparency': 1.0},
 {'time': 4.1701109409332275,
  'obj': 0.511869693294053,
  'best_bound': 15.000000000000897,
  'gap': 28.3043331076526,
  'train_acc': 0.5118696932940565,
  'train_transparency': 1.0},
 {'time': 69.53902077674866,
  'obj': 0.5355823600762393,
  'best_bound': 0.999850000000013,
  'gap': 0.8668463984842332,
  'train_acc': 0.5357823600762432,
  'train_transparency': 1.0},
 {'time': 69.7161808013916,
  'obj': 0.5366200311904298,
  'best_bound': 0.999850000000013,
  'gap': 0.8632364464329833,
  'train_acc': 0.5368220412406862,
  'train_transparency': 0.9597989949748744},
 {'time': 69.82375693321228,
  'obj': 0.5366211575116921,
  'best_bound': 0.999850000000013,
  'gap': 0.8632325356613019,
  'train_acc': 0.5368220412406862,
  'train_transparency': 0.9823254202044707},
 {'time': 69.88840889930725,
  'obj': 0.5367933373765328,
  'best_bound': 0.999850000000013,
  'gap': 0.8626348920174282,
  'train_acc': 0.53699532143476,
  'train_transparency': 0.9603188355570959},
 {'time': 86.20882201194763,
  'obj': 0.5859735054583198,
  'best_bound': 0.9998499999999936,
  'gap': 0.7063058153422138,
  'train_acc': 0.586380176745798,
  'train_transparency': 0.8665742505631606},
 {'time': 86.27461099624634,
  'obj': 0.5937711141916413,
  'best_bound': 0.9998499999999936,
  'gap': 0.6838980140709391,
  'train_acc': 0.5941777854791197,
  'train_transparency': 0.8665742505631606},
 {'time': 86.3926899433136,
  'obj': 0.6329266504938413,
  'best_bound': 0.9998499999999936,
  'gap': 0.5797249163388208,
  'train_acc': 0.6333391093398024,
  'train_transparency': 0.7508230809218506},
 {'time': 86.61863684654236,
  'obj': 0.6452295442730821,
  'best_bound': 0.9998499999999936,
  'gap': 0.5496035618245413,
  'train_acc': 0.6456420031190435,
  'train_transparency': 0.7508230809218506},
 {'time': 87.00734496116638,
  'obj': 0.6455744151793374,
  'best_bound': 0.9998499999999936,
  'gap': 0.5487757514712538,
  'train_acc': 0.6459885635071911,
  'train_transparency': 0.7170334430774563},
 {'time': 150.02755188941956,
  'obj': 0.6554510136891317,
  'best_bound': 0.9998458448405759,
  'gap': 0.5254318384726525,
  'train_acc': 0.6558655345693987,
  'train_transparency': 0.7095823947322821},
 {'time': 150.31259083747864,
  'obj': 0.6752061774389126,
  'best_bound': 0.9998458448405759,
  'gap': 0.48080079574069673,
  'train_acc': 0.675619476693814,
  'train_transparency': 0.7340149020966904},
 {'time': 158.06805086135864,
  'obj': 0.6819644169121435,
  'best_bound': 0.9998458448405759,
  'gap': 0.466126120432739,
  'train_acc': 0.6823774042626928,
  'train_transparency': 0.7402529890833478}]